#!/usr/bin/env node
/**
 * Generate src/utils/pdf/fontData.ts from the Amiri-Regular TTF.
 * Embedding as a base64 JS module keeps the font available identically on
 * Android, iOS and Jest without relying on Metro's asset pipeline.
 *
 * Usage: node scripts/gen_font_module.js <path-to-ttf>
 */
const fs = require('fs');
const path = require('path');

const [, , ttfPath] = process.argv;
if (!ttfPath) {
  console.error('usage: node scripts/gen_font_module.js <Amiri-Regular.ttf>');
  process.exit(1);
}

const ttf = fs.readFileSync(ttfPath);
const b64 = ttf.toString('base64');

// Chunk the base64 into ~100k lines so editors/linters stay happy.
const lines = [];
for (let i = 0; i < b64.length; i += 100000) {
  lines.push(b64.slice(i, i + 100000));
}

const out = `/**
 * Amiri Regular (SIL Open Font License 1.1) embedded as base64.
 *
 * Amiri is the reference font for Unicode Arabic Presentation Forms — the
 * codepoints produced by arabicShaper.ts — which is why it backs PDF chat
 * exports. Generated by scripts/gen_font_module.js; DO NOT edit by hand.
 *
 * Font copyright (c) 2010-2022 The Amiri Project Authors
 * (https://github.com/aliftype/amiri), licensed under the SIL OFL 1.1 —
 * see Amiri-OFL.txt alongside this file.
 */
/* eslint-disable prettier/prettier */
export const AMIRI_FONT_BASE64 = [
${lines.map(l => `  '${l}',`).join('\n')}
].join('');
`;
const dest = path.join(__dirname, '..', 'src', 'utils', 'pdf', 'fontData.ts');
fs.writeFileSync(dest, out);
console.log(`wrote ${dest} (${(out.length / 1024).toFixed(0)} KB)`);
